spring:
    application:
        name: simpleMS

    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: admin
        password: admin

    r2dbc:
        url: r2dbc:h2:mem:///testdb
        username: admin
        password: admin

    jpa:
        hibernate:
            ddl-auto: update