spring:
    application:
        name: simpleMS
    r2dbc:
        url: r2dbc:mysql://localhost:3306/simple-orders
        username: root
        password: Colombia1
    flyway:
        url: jdbc:mysql://localhost:3306/simple-orders
        user: root
        password: Colombia1
        locations: classpath:db/migration
        baseline-on-migrate: true